### ISSUE TITLE
Take it down

### ISSUE THREAD

**Issue by Tr1Fecta-7** [Kanns103/GuideToTweakDevelopment13-14#1]

**Comment by Tr1Fecta-7** [comment]
Feel free to message me, if you wanna know whats wrong exactly

**Comment by Kanns103** [comment]
Honestly, I’ve explained this so many times and it’s kinda annoying now. I used layoutSubviews because it’s the easiest way to do things. I know it’s wrong, but for the purpose of the demonstration, I used it. I created this guide for people who have 0 code knowledge.

**Comment by Burrit0z** [comment]
Well then maybe don’t teach them how to do it the wrong way, and leave them in a position where they don’t know any better than to hook something like this.

**Comment by CharlieWhile13** [comment]
> I know it’s wrong

Don't teach people the wrong thing, it's not helpful in any way. 
> who have 0 code knowledge

You need to know how to code before you can program anything.

**Comment by Burrit0z** [comment]
You're really deleting comments? Smh, Do better.

**Comment by Tr1Fecta-7** [comment]
You taking L's on L, deleting comments now. Childish, instead of learning how to properly code tweaks clown

**Comment by tale** [comment]
Imagine being an idiot

**Comment by tale** [comment]
Bro, stop deleting our comments just cuz your stupid and don't know how to do proper tweak development.

**Comment by Kanns103** [comment]
It’s a shame because I made this tutorial for people to learn from, it took me hours. I’ve explained many times why I used layoutSubviews and it was JUST AN EXAMPLE. Many open sourced projects and projects them selves use it. layoutSubviews is not used for everything and I’m quite aware as to why it shouldn’t be used. 

I’m deleting your comments because they’re nasty and do not relate to the original comment. Saying I’m childish and calling me a clown? Calling me an idiot? Saying I’m stupid and that I don’t know how to do proper tweak development? You’re all saying this because I deleted a few comments that were useless and horrible. You guys ‘improved’ my guide but all that it did was add a link to another guide at the bottom.

You guys must have been learning at some point. Did you have people shoot you down and call you names? What would be really helpful would be constructive feedback and not name calling, which doesn’t help anybody. I know you’re all going to reply saying this and that and how ‘it wasn’t mean’ or whatever, but it was and you know it. 

It’s sad because i’m a nice guy and hate drama, so when you say stuff like this, it doesn’t make me want to take it down or quit development, it fuels me. So carry on calling me a clown, or an idiot or that I’m childish as it does not effect me.

**Comment by Tr1Fecta-7** [comment]
If you are/were aware of why it shouldn't be used, you shouldn't be using it as example at all. It's just gonna let people who are new to tweak development use your example as "correct" and then we end up with tweaks that are horribly coded. I asked you to message me, if you wanted to know why and how you could correct the guide, but no instead you edited my message and deleted the rest of the comments, which makes it definitely look like you can't take any criticism and aren't willing to listen.

**Comment by Kanns103** [comment]
No I’m 100% sure I can take ‘Criticism’ because I’ve updated the guide with everybody’s ‘criticism’. And you think I want ‘criticism’ from somebody like you who called me childish and a clown?
